### ISSUE TITLE
你好我在MobileVit的pth转onnx过程中遇到了一些问题

### ISSUE THREAD

**Issue by liu-ai-z** [chenlamei/MobileVit_TensorRT#2]
在转化过程中，有两个warring, D:\Miniconda\envs\py38\lib\site-packages\einops\einops.py:315: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  unknown = {axis for axis in composite_axis if axis_name2known_length[axis] == _unknown_axis_length}
虽然能够转成onnx，但转出来某一个分类结果非常差，其他类别结果没问题，你遇到过这个问题吗？我不知道是不是这两个warring 引起的

**Comment by chenlamei** [comment]
转换过程中的确会有warring ，但感觉你的模型问题不在这里，尤其是“某一个分类结果非常差，其他类别结果没问题”。不知你是否用了INT8的trt，如果是int8的有可能是量化引起的，我建议你先验证一下fp16或是FP32的模型精度是否有问题
