### ISSUE TITLE
关于qat只量化weight

### ISSUE THREAD

**Issue by Nusselder9** [chenlamei/MobileVit_TensorRT#4]
cool work！关于qat有个问题想请教：

> “后面通过简化版的QAT（训练中只对weight进行量化，feature map不量化）提高了量化精度，最终量化后top1 acc精度仅下降0.3个百分点，top5下降 0.25个百分点”

请问（1）top1 acc精度仅下降0.3，这个结果对feature也量化了吗？还是只量化了weight？
（2）如果feature也量化了，是先qat只量化weight，再用IInt8EntropyCalibrator2量化feature吗，这样为什么比直接IInt8EntropyCalibrator2量化精度好呢？

感谢！

**Comment by chenlamei** [comment]
（1）部署时feature和weight均被量化了
（2）模型量化包括feature量化和weight量化，实际项目中在QAT时应该都对他们进行伪量化操作。本项目时间原因就只对weight添加了伪量化节点，feature 量化参数由IInt8EntropyCalibrator2计算得到；因为对weight进行了伪量化所以相比“直接IInt8EntropyCalibrator2”weight量化损失基本没有，精度更高
